### ISSUE TITLE
UI Issues - UI/UX team

### ISSUE THREAD

**Issue by sijumoncy** [bible-technology/scribe-scripture-editor#230]
- [x] New project page has a responsive issue - when the window is minimised the input boxes are overlapping with other column input boxes

**Comment by selvabenz** [comment]
- [x] LTR icon is floating everywhere
- [x] Overflow in the Advance setting dropdown
- [x] The left side panel does not have full height
- [x] Advanced settings expansion overflow
- [x] Overall responsiveness of the app UI

**Comment by yakob-aleksandrovich** [comment]
(In Linux)
- [ ] Hitting CTRL+R (Browser reload) in the New Project window makes the window go blank
- [x] Resizing the window in New Project window messes up the layout
![image](https://github.com/bible-technology/scribe-scripture-editor/assets/16293781/eca2ce9d-af27-44a0-bf33-3add7c41c10e)

**Comment by selvabenz** [comment]
- Resizing the window in New Project window messes up the layout
![image](https://github.com/bible-technology/scribe-scripture-editor/assets/121541505/a06f15aa-77b0-4823-8279-42164798372c)
-  LTR icon is floating everywhere
- Overflow in the Advance setting dropdown
- The left side panel does not have full height
- Advanced settings expansion overflow
- Overall responsiveness of the app UI

All the mentioned issues have been fixed in version 0.5.5

**Comment by selvabenz** [comment]
- Hitting CTRL+R (Browser reload) in the New Project window makes the window go blank. this is the expected result.
